######################################################################
# Automatically generated by qmake (3.1) Mon May 15 03:51:23 2017
######################################################################

TEMPLATE = app
TARGET = run
INCLUDEPATH += .
QT += core network widgets testlib
CONFIG += c++14

# Input
SOURCES += main.cpp\
    result_handler.cpp

HEADERS += tests.h\
    ../../src/network/network.h\
    ../../src/ui/dialogs.h
